[package]
name = "uc-intg-hass"
version = "0.1.0"
edition = "2021"
authors = ["Markus Zehnder <markus.z@unfoldedcircle.com>"]
license = "MPL-2.0"
description = "Unfolded Circle Home-Assistant integration for Remote Two"
#repository = "https://github.com/TODO"
#documentation = "TODO"

[dependencies]
# Attention: New commits will not be pulled down automatically once the lock is in place.
# Update to latest snapshot: `cargo update -p uc_api`
uc_api = { git = "https://github.com/unfoldedcircle/api-model-rs" }
# for local development:
#uc_api = { path = "../api-model-rs" }

# WebSockets server
actix-web = { version = "4.0.1", features = ["rustls"] }
actix-web-actors = "4.1.0"
actix = "0.12"
actix-tls = { version = "3.0.3", features = ["rustls"] }
bytestring = "1"
rustls = "0.20"
rustls-pemfile = "1.0.0"
# WebSockets client
actix-codec = "0.5"
awc = { version = "3.0.0", features = ["rustls"] }
bytes = "1"
futures = "0.3"

# JSON (de)serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "1"

config = { version = "0.13", default-features = false, features = ["yaml"] }

env_logger = "0.9"
log = "0.4"

uuid = { version = "1.0.0", features = ["v4"] }
url = { version = "2", features = ["serde"] }
time = { version = "0.3", default-features = false, features = ["std", "formatting"] }

# Helpful macros for working with enums and strings
strum = "0.24"
strum_macros = "0.24"
derive_more = "0.99"

[dev-dependencies]
rstest = "0.13"
