integration:
  interface: 0.0.0.0
  http:
    enabled: true
    port: 8000
  https:
    enabled: false
    port: 8443
  certs:
    public: certs/local-cert.pem
    private: certs/local-key.pem
  websocket:
    #token: 1-2-3
    heartbeat:
      interval_sec: 10
      timeout_sec: 20
