webserver:
  interface: 0.0.0.0
  http: true
  http_port: 8000
  https: false
  https_port: 8443
home_assistant:
  url: ws://hassio.local:8123/api/websocket
  token: YOUR_HA_TOKEN
  connection_timeout: 3
  #disable_cert_validation: no
  reconnect:
    attempts: 10
    duration_ms: 1000
    duration_max_ms: 20000
    backoff_factor: 1.5
  heartbeat:
    interval_sec: 30
    timeout_sec: 40
