name: Security audit
on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/**/audit-on-push.yml'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: intg-hass
      # BEGIN temporary workaround until api-model-rs is public
      - name: Checkout API model crate
        uses: actions/checkout@v3
        with:
          repository: aitatoi/api-model-rs
          path: api-model-rs
          token: ${{ secrets.PAT_BUILD_USER }}
      - name: Create Workspace
        run: |
          cat > Cargo.toml << ENDOFFILE
          [workspace]
          members = [
          "api-model-rs",
          "intg-hass",
          ]  
          ENDOFFILE
          cp intg-hass/Cargo.lock ./
      # END workaround
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}